// This file is not generated by Stainless and is preserved across codegen runs.
// It holds unit tests for the hand-written *AndPoll convenience methods that
// were isolated into cloud/*_custom.go.
//
// The tests are self-contained: each drives a local httptest.Server that
// emulates the Cloud async task flow, so they run under a plain `go test` (or
// `scripts/test`) without needing the Prism/Steady mock server.

package cloud_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/G-Core/gcore-go"
	"github.com/G-Core/gcore-go/cloud"
	"github.com/G-Core/gcore-go/option"
)

const andPollCreatedID = "00000000-0000-4000-8000-000000000001"

// createdResourceStringFields lists every string field of TaskCreatedResources.
// The fake task server populates all of them with a single ID so that any
// NewAndPoll-style method finds exactly the one created resource it looks for.
var createdResourceStringFields = []string{
	"ai_clusters", "api_keys", "caas_containers", "clusters", "faas_functions",
	"faas_namespaces", "file_shares", "floatingips", "healthmonitors", "images",
	"inference_instances", "instances", "k8s_clusters", "k8s_pools", "l7polices",
	"l7rules", "laas_topic", "listeners", "loadbalancers", "members", "networks",
	"pools", "ports", "postgresql_clusters", "registry_registries", "registry_users",
	"routers", "secrets", "security_group_rules", "security_groups", "servergroups",
	"snapshots", "subnets", "volumes",
}

// taskFlowConfig configures the fake Cloud task server.
type taskFlowConfig struct {
	// actionTasks is the task ID list returned by the mutating action
	// (POST/PATCH/DELETE). nil means the default single task; a non-nil empty
	// slice emulates a no-op update where the API creates no task.
	actionTasks *[]string
	// taskState reported for the polled task; defaults to FINISHED.
	taskState cloud.TaskState
	// taskError reported when taskState == ERROR.
	taskError string
}

// newTaskFlowServer returns an httptest.Server emulating the Cloud async flow:
//   - a mutating request (the action) returns a TaskIDList
//   - GET .../tasks/{id} returns a task in the configured state, with every
//     created_resources field populated so any *AndPoll method finds its resource
//   - any other GET (the final resource fetch) returns an empty JSON object
func newTaskFlowServer(cfg taskFlowConfig) *httptest.Server {
	tasks := []string{"task-1"}
	if cfg.actionTasks != nil {
		tasks = *cfg.actionTasks
	}
	state := cfg.taskState
	if state == "" {
		state = cloud.TaskStateFinished
	}
	created := map[string]any{"projects": []int64{1}, "ddos_profiles": []int64{1}}
	for _, f := range createdResourceStringFields {
		created[f] = []string{andPollCreatedID}
	}

	// task mirrors the shape of a real GET /v1/tasks/{id} response (captured from
	// the Cloud API — a FINISHED create_fip task), so the custom parsing code is
	// exercised against a realistic payload. state/error/created_resources are
	// overridden per test; created_resources is a superset carrying one ID under
	// every field so any NewAndPoll method finds its resource.
	var errVal any
	if cfg.taskError != "" {
		errVal = cfg.taskError
	}
	task := map[string]any{
		"id":                  "50e2042d-761b-4f5a-b5bf-e11031c747b0",
		"state":               state,
		"task_type":           "create_fip",
		"client_id":           3621,
		"user_id":             4585,
		"user_client_id":      3621,
		"project_id":          379987,
		"region_id":           76,
		"detailed_state":      nil,
		"request_id":          "01601532933a3a7e7a71f935befd1dd1",
		"error":               errVal,
		"created_on":          "2026-07-01T13:37:14",
		"updated_on":          "2026-07-01T13:37:17",
		"finished_on":         "2026-07-01T13:37:17",
		"acknowledged_at":     nil,
		"acknowledged_by":     nil,
		"job_id":              nil,
		"schedule_id":         nil,
		"lifecycle_policy_id": nil,
		"created_resources":   created,
	}

	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && strings.Contains(r.URL.Path, "/tasks/"):
			_ = json.NewEncoder(w).Encode(task)
		case r.Method == http.MethodGet:
			// The final resource fetch (or List). Most *AndPoll methods return this
			// value unmodified, so an empty object suffices; but a few re-fetch the
			// parent and search a nested collection for the just-created child
			// (BaremetalServer via List.results, LoadBalancerPoolMember via
			// pool.members, SecurityGroupRule via sg.security_group_rules), and
			// InstanceImage.UploadAndPoll polls the image until it reports
			// status "active" with a non-zero size. The superset below carries the
			// created ID in each of those collections plus a settled image state so
			// the lookups succeed; unrelated resource types ignore the extra fields.
			_ = json.NewEncoder(w).Encode(map[string]any{
				"count":                1,
				"results":              []map[string]any{{"id": andPollCreatedID}},
				"members":              []map[string]any{{"id": andPollCreatedID}},
				"security_group_rules": []map[string]any{{"id": andPollCreatedID}},
				"status":               "active",
				"size":                 1,
			})
		default: // the action: New/Update/Delete/Resize/Action/...
			_ = json.NewEncoder(w).Encode(map[string]any{"tasks": tasks})
		}
	}))
}

func newTaskFlowClient(server *httptest.Server, opts ...option.RequestOption) gcore.Client {
	return gcore.NewClient(append([]option.RequestOption{
		option.WithBaseURL(server.URL),
		option.WithAPIKey("test"),
		// Project/region defaults satisfy the required path params that the
		// generated methods validate before issuing a request.
		option.WithCloudProjectID(1),
		option.WithCloudRegionID(1),
	}, opts...)...)
}

// andPollMethods enumerates every *AndPoll convenience method across the cloud
// services (generated from cloud/*_custom.go). Each invoke drives the method
// with zero-value params — the fake server ignores request bodies — and returns
// only the error so the happy-path test can assert success uniformly.
var andPollMethods = []struct {
	name   string
	invoke func(ctx context.Context, client gcore.Client) error
}{
	{"BaremetalServer.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Baremetal.Servers.DeleteAndPoll(ctx, "id", cloud.BaremetalServerDeleteParams{})
	}},
	{"BaremetalServer.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Baremetal.Servers.NewAndPoll(ctx, cloud.BaremetalServerNewParams{})
		return err
	}},
	{"BaremetalServer.RebuildAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Baremetal.Servers.RebuildAndPoll(ctx, "id", cloud.BaremetalServerRebuildParams{})
		return err
	}},
	{"DatabasePostgresCluster.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Databases.Postgres.Clusters.DeleteAndPoll(ctx, "id", cloud.DatabasePostgresClusterDeleteParams{})
	}},
	{"DatabasePostgresCluster.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Databases.Postgres.Clusters.NewAndPoll(ctx, cloud.DatabasePostgresClusterNewParams{})
		return err
	}},
	{"DatabasePostgresCluster.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Databases.Postgres.Clusters.UpdateAndPoll(ctx, "id", cloud.DatabasePostgresClusterUpdateParams{})
		return err
	}},
	{"FileShare.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.FileShares.DeleteAndPoll(ctx, "id", cloud.FileShareDeleteParams{})
	}},
	{"FileShare.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FileShares.NewAndPoll(ctx, cloud.FileShareNewParams{})
		return err
	}},
	{"FileShare.ResizeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FileShares.ResizeAndPoll(ctx, "id", cloud.FileShareResizeParams{})
		return err
	}},
	{"FileShare.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FileShares.UpdateAndPoll(ctx, "id", cloud.FileShareUpdateParams{})
		return err
	}},
	{"FloatingIP.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.FloatingIPs.DeleteAndPoll(ctx, "id", cloud.FloatingIPDeleteParams{})
	}},
	{"FloatingIP.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FloatingIPs.NewAndPoll(ctx, cloud.FloatingIPNewParams{})
		return err
	}},
	{"FloatingIP.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FloatingIPs.UpdateAndPoll(ctx, "id", cloud.FloatingIPUpdateParams{})
		return err
	}},
	{"GPUBaremetalCluster.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUBaremetal.Clusters.DeleteAndPoll(ctx, "id", cloud.GPUBaremetalClusterDeleteParams{})
	}},
	{"GPUBaremetalCluster.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUBaremetal.Clusters.NewAndPoll(ctx, cloud.GPUBaremetalClusterNewParams{})
		return err
	}},
	{"GPUBaremetalCluster.RebuildAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUBaremetal.Clusters.RebuildAndPoll(ctx, "id", cloud.GPUBaremetalClusterRebuildParams{})
		return err
	}},
	{"GPUBaremetalCluster.ResizeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUBaremetal.Clusters.ResizeAndPoll(ctx, "id", cloud.GPUBaremetalClusterResizeParams{})
		return err
	}},
	{"GPUBaremetalClusterImage.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUBaremetal.Clusters.Images.DeleteAndPoll(ctx, "id", cloud.GPUBaremetalClusterImageDeleteParams{})
	}},
	{"GPUBaremetalClusterImage.UploadAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUBaremetal.Clusters.Images.UploadAndPoll(ctx, cloud.GPUBaremetalClusterImageUploadParams{})
		return err
	}},
	{"GPUBaremetalClusterInterface.AttachAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUBaremetal.Clusters.Interfaces.AttachAndPoll(ctx, "id", cloud.GPUBaremetalClusterInterfaceAttachParams{})
	}},
	{"GPUBaremetalClusterInterface.DetachAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUBaremetal.Clusters.Interfaces.DetachAndPoll(ctx, "id", cloud.GPUBaremetalClusterInterfaceDetachParams{})
	}},
	{"GPUBaremetalClusterServer.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUBaremetal.Clusters.Servers.DeleteAndPoll(ctx, "id", cloud.GPUBaremetalClusterServerDeleteParams{ClusterID: "id"})
	}},
	{"GPUBaremetalClusterServer.RebuildAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUBaremetal.Clusters.Servers.RebuildAndPoll(ctx, "id", cloud.GPUBaremetalClusterServerRebuildParams{ClusterID: "id"})
		return err
	}},
	{"GPUBaremetalClusterServer.ReplaceAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUBaremetal.Clusters.Servers.ReplaceAndPoll(ctx, "id", cloud.GPUBaremetalClusterServerReplaceParams{ClusterID: "id"})
		return err
	}},
	{"GPUVirtualCluster.ActionAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUVirtual.Clusters.ActionAndPoll(ctx, "id", cloud.GPUVirtualClusterActionParams{})
		return err
	}},
	{"GPUVirtualCluster.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUVirtual.Clusters.DeleteAndPoll(ctx, "id", cloud.GPUVirtualClusterDeleteParams{})
	}},
	{"GPUVirtualCluster.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUVirtual.Clusters.NewAndPoll(ctx, cloud.GPUVirtualClusterNewParams{})
		return err
	}},
	{"GPUVirtualClusterImage.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUVirtual.Clusters.Images.DeleteAndPoll(ctx, "id", cloud.GPUVirtualClusterImageDeleteParams{})
	}},
	{"GPUVirtualClusterImage.UploadAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.GPUVirtual.Clusters.Images.UploadAndPoll(ctx, cloud.GPUVirtualClusterImageUploadParams{})
		return err
	}},
	{"GPUVirtualClusterServer.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.GPUVirtual.Clusters.Servers.DeleteAndPoll(ctx, "id", cloud.GPUVirtualClusterServerDeleteParams{ClusterID: "id"})
	}},
	{"InferenceDeployment.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Inference.Deployments.DeleteAndPoll(ctx, "id", cloud.InferenceDeploymentDeleteParams{})
	}},
	{"InferenceDeployment.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Inference.Deployments.NewAndPoll(ctx, cloud.InferenceDeploymentNewParams{})
		return err
	}},
	{"InferenceDeployment.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Inference.Deployments.UpdateAndPoll(ctx, "id", cloud.InferenceDeploymentUpdateParams{})
		return err
	}},
	{"Instance.ActionAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.ActionAndPoll(ctx, "id", cloud.InstanceActionParams{})
		return err
	}},
	{"Instance.AddToPlacementGroupAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.AddToPlacementGroupAndPoll(ctx, "id", cloud.InstanceAddToPlacementGroupParams{})
		return err
	}},
	{"Instance.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Instances.DeleteAndPoll(ctx, "id", cloud.InstanceDeleteParams{})
	}},
	{"Instance.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.NewAndPoll(ctx, cloud.InstanceNewParams{})
		return err
	}},
	{"Instance.RemoveFromPlacementGroupAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.RemoveFromPlacementGroupAndPoll(ctx, "id", cloud.InstanceRemoveFromPlacementGroupParams{})
		return err
	}},
	{"Instance.ResizeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.ResizeAndPoll(ctx, "id", cloud.InstanceResizeParams{})
		return err
	}},
	{"InstanceImage.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Instances.Images.DeleteAndPoll(ctx, "id", cloud.InstanceImageDeleteParams{})
	}},
	{"InstanceImage.NewFromVolumeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.Images.NewFromVolumeAndPoll(ctx, cloud.InstanceImageNewFromVolumeParams{})
		return err
	}},
	{"InstanceImage.UploadAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Instances.Images.UploadAndPoll(ctx, cloud.InstanceImageUploadParams{})
		return err
	}},
	{"InstanceInterface.AttachAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Instances.Interfaces.AttachAndPoll(ctx, "id", cloud.InstanceInterfaceAttachParams{})
	}},
	{"InstanceInterface.DetachAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Instances.Interfaces.DetachAndPoll(ctx, "id", cloud.InstanceInterfaceDetachParams{})
	}},
	{"K8SCluster.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.K8S.Clusters.DeleteAndPoll(ctx, "id", cloud.K8SClusterDeleteParams{})
	}},
	{"K8SCluster.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.K8S.Clusters.NewAndPoll(ctx, cloud.K8SClusterNewParams{Name: "id"})
		return err
	}},
	{"K8SCluster.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.K8S.Clusters.UpdateAndPoll(ctx, "id", cloud.K8SClusterUpdateParams{})
		return err
	}},
	{"K8SCluster.UpgradeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.K8S.Clusters.UpgradeAndPoll(ctx, "id", cloud.K8SClusterUpgradeParams{})
		return err
	}},
	{"K8SClusterPool.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.K8S.Clusters.Pools.DeleteAndPoll(ctx, "id", cloud.K8SClusterPoolDeleteParams{ClusterName: "id"})
	}},
	{"K8SClusterPool.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.K8S.Clusters.Pools.NewAndPoll(ctx, "id", cloud.K8SClusterPoolNewParams{Name: "id"})
		return err
	}},
	{"K8SClusterPool.ResizeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.K8S.Clusters.Pools.ResizeAndPoll(ctx, "id", cloud.K8SClusterPoolResizeParams{ClusterName: "id"})
		return err
	}},
	{"LoadBalancer.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.LoadBalancers.DeleteAndPoll(ctx, "id", cloud.LoadBalancerDeleteParams{})
	}},
	{"LoadBalancer.FailoverAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.FailoverAndPoll(ctx, "id", cloud.LoadBalancerFailoverParams{})
		return err
	}},
	{"LoadBalancer.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.NewAndPoll(ctx, cloud.LoadBalancerNewParams{})
		return err
	}},
	{"LoadBalancer.ResizeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.ResizeAndPoll(ctx, "id", cloud.LoadBalancerResizeParams{})
		return err
	}},
	{"LoadBalancerL7Policy.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.LoadBalancers.L7Policies.DeleteAndPoll(ctx, "id", cloud.LoadBalancerL7PolicyDeleteParams{})
	}},
	{"LoadBalancerL7Policy.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.L7Policies.NewAndPoll(ctx, cloud.LoadBalancerL7PolicyNewParams{})
		return err
	}},
	{"LoadBalancerL7Policy.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.L7Policies.UpdateAndPoll(ctx, "id", cloud.LoadBalancerL7PolicyUpdateParams{})
		return err
	}},
	{"LoadBalancerL7PolicyRule.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.LoadBalancers.L7Policies.Rules.DeleteAndPoll(ctx, "id", cloud.LoadBalancerL7PolicyRuleDeleteParams{L7policyID: "id"})
	}},
	{"LoadBalancerL7PolicyRule.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.L7Policies.Rules.NewAndPoll(ctx, "id", cloud.LoadBalancerL7PolicyRuleNewParams{})
		return err
	}},
	{"LoadBalancerL7PolicyRule.ReplaceAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.L7Policies.Rules.ReplaceAndPoll(ctx, "id", cloud.LoadBalancerL7PolicyRuleReplaceParams{L7policyID: "id"})
		return err
	}},
	{"LoadBalancerListener.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.LoadBalancers.Listeners.DeleteAndPoll(ctx, "id", cloud.LoadBalancerListenerDeleteParams{})
	}},
	{"LoadBalancerListener.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Listeners.NewAndPoll(ctx, cloud.LoadBalancerListenerNewParams{})
		return err
	}},
	{"LoadBalancerListener.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Listeners.UpdateAndPoll(ctx, "id", cloud.LoadBalancerListenerUpdateParams{})
		return err
	}},
	{"LoadBalancerPool.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.LoadBalancers.Pools.DeleteAndPoll(ctx, "id", cloud.LoadBalancerPoolDeleteParams{})
	}},
	{"LoadBalancerPool.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Pools.NewAndPoll(ctx, cloud.LoadBalancerPoolNewParams{})
		return err
	}},
	{"LoadBalancerPool.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Pools.UpdateAndPoll(ctx, "id", cloud.LoadBalancerPoolUpdateParams{})
		return err
	}},
	{"LoadBalancerPoolMember.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.LoadBalancers.Pools.Members.DeleteAndPoll(ctx, "id", cloud.LoadBalancerPoolMemberDeleteParams{PoolID: "id"})
	}},
	{"LoadBalancerPoolMember.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Pools.Members.NewAndPoll(ctx, "id", cloud.LoadBalancerPoolMemberNewParams{})
		return err
	}},
	{"Network.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Networks.DeleteAndPoll(ctx, "id", cloud.NetworkDeleteParams{})
	}},
	{"Network.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Networks.NewAndPoll(ctx, cloud.NetworkNewParams{})
		return err
	}},
	{"NetworkRouter.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Networks.Routers.DeleteAndPoll(ctx, "id", cloud.NetworkRouterDeleteParams{})
	}},
	{"NetworkRouter.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Networks.Routers.NewAndPoll(ctx, cloud.NetworkRouterNewParams{})
		return err
	}},
	{"NetworkRouter.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Networks.Routers.UpdateAndPoll(ctx, "id", cloud.NetworkRouterUpdateParams{})
		return err
	}},
	{"NetworkSubnet.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Networks.Subnets.DeleteAndPoll(ctx, "id", cloud.NetworkSubnetDeleteParams{})
	}},
	{"NetworkSubnet.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Networks.Subnets.NewAndPoll(ctx, cloud.NetworkSubnetNewParams{})
		return err
	}},
	{"PlacementGroup.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.PlacementGroups.DeleteAndPoll(ctx, "id", cloud.PlacementGroupDeleteParams{})
	}},
	{"Project.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Projects.DeleteAndPoll(ctx, cloud.ProjectDeleteParams{})
	}},
	{"ReservedFixedIP.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.ReservedFixedIPs.DeleteAndPoll(ctx, "id", cloud.ReservedFixedIPDeleteParams{})
	}},
	{"ReservedFixedIP.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.ReservedFixedIPs.NewAndPoll(ctx, cloud.ReservedFixedIPNewParams{})
		return err
	}},
	{"Secret.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Secrets.DeleteAndPoll(ctx, "id", cloud.SecretDeleteParams{})
	}},
	{"Secret.UploadTlsCertificateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Secrets.UploadTlsCertificateAndPoll(ctx, cloud.SecretUploadTlsCertificateParams{})
		return err
	}},
	{"SecurityGroup.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.SecurityGroups.NewAndPoll(ctx, cloud.SecurityGroupNewParams{})
		return err
	}},
	{"SecurityGroup.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.SecurityGroups.UpdateAndPoll(ctx, "id", cloud.SecurityGroupUpdateParams{})
		return err
	}},
	{"SecurityGroupRule.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.SecurityGroups.Rules.DeleteAndPoll(ctx, "id", cloud.SecurityGroupRuleDeleteParams{GroupID: "id"})
	}},
	{"SecurityGroupRule.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.SecurityGroups.Rules.NewAndPoll(ctx, "id", cloud.SecurityGroupRuleNewParams{})
		return err
	}},
	{"Volume.AttachToInstanceAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Volumes.AttachToInstanceAndPoll(ctx, "id", cloud.VolumeAttachToInstanceParams{})
	}},
	{"Volume.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Volumes.DeleteAndPoll(ctx, "id", cloud.VolumeDeleteParams{})
	}},
	{"Volume.DetachFromInstanceAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.Volumes.DetachFromInstanceAndPoll(ctx, "id", cloud.VolumeDetachFromInstanceParams{})
	}},
	{"Volume.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Volumes.NewAndPoll(ctx, cloud.VolumeNewParams{})
		return err
	}},
	{"Volume.ResizeAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Volumes.ResizeAndPoll(ctx, "id", cloud.VolumeResizeParams{})
		return err
	}},
	{"VolumeSnapshot.DeleteAndPoll", func(ctx context.Context, client gcore.Client) error {
		return client.Cloud.VolumeSnapshots.DeleteAndPoll(ctx, "id", cloud.VolumeSnapshotDeleteParams{})
	}},
	{"VolumeSnapshot.NewAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.VolumeSnapshots.NewAndPoll(ctx, cloud.VolumeSnapshotNewParams{})
		return err
	}},
}

// TestAndPollMethodsSucceed exercises every *AndPoll method end-to-end against
// the fake task flow and asserts each completes without error. This guards the
// wiring of the isolated custom code: action -> poll task -> (extract created
// resource) -> get.
func TestAndPollMethodsSucceed(t *testing.T) {
	server := newTaskFlowServer(taskFlowConfig{})
	defer server.Close()
	client := newTaskFlowClient(server)

	for _, tc := range andPollMethods {
		t.Run(tc.name, func(t *testing.T) {
			if err := tc.invoke(context.Background(), client); err != nil {
				t.Fatalf("%s returned an unexpected error: %s", tc.name, err)
			}
		})
	}
}

// TestAndPollMethodsCount is a canary: if codegen or a spec change adds/removes
// an *AndPoll method, this reminds us to keep the table in sync.
func TestAndPollMethodsCount(t *testing.T) {
	const want = 93
	if got := len(andPollMethods); got != want {
		t.Fatalf("andPollMethods has %d entries, want %d; update the table in this file", got, want)
	}
}

// TestNewAndPollRequiresTask verifies a NewAndPoll method surfaces an error when
// the API creates no task (a New must always create exactly one).
func TestNewAndPollRequiresTask(t *testing.T) {
	empty := []string{}
	server := newTaskFlowServer(taskFlowConfig{actionTasks: &empty})
	defer server.Close()
	client := newTaskFlowClient(server)

	if _, err := client.Cloud.FloatingIPs.NewAndPoll(context.Background(), cloud.FloatingIPNewParams{}); err == nil {
		t.Fatal("NewAndPoll with no created task should return an error")
	}
}

// TestTaskServicePoll covers the shared TaskService.Poll loop that every
// *AndPoll method relies on.
func TestTaskServicePoll(t *testing.T) {
	t.Run("finished", func(t *testing.T) {
		server := newTaskFlowServer(taskFlowConfig{taskState: cloud.TaskStateFinished})
		defer server.Close()
		client := newTaskFlowClient(server)

		task, err := client.Cloud.Tasks.Poll(context.Background(), "task-1")
		if err != nil {
			t.Fatalf("Poll returned an unexpected error: %s", err)
		}
		if task.State != cloud.TaskStateFinished {
			t.Fatalf("Poll returned state %q, want FINISHED", task.State)
		}
	})

	t.Run("error", func(t *testing.T) {
		server := newTaskFlowServer(taskFlowConfig{taskState: cloud.TaskStateError, taskError: "boom"})
		defer server.Close()
		client := newTaskFlowClient(server)

		_, err := client.Cloud.Tasks.Poll(context.Background(), "task-1")
		if err == nil {
			t.Fatal("Poll should return an error for a task in ERROR state")
		}
		if !strings.Contains(err.Error(), "boom") {
			t.Fatalf("Poll error %q should mention the task error %q", err.Error(), "boom")
		}
	})

	t.Run("context timeout", func(t *testing.T) {
		// Task never reaches a terminal state, so Poll loops until the context
		// deadline. The min polling interval is 1s, so a short deadline wins
		// deterministically after the first status check.
		server := newTaskFlowServer(taskFlowConfig{taskState: cloud.TaskStateRunning})
		defer server.Close()
		client := newTaskFlowClient(server)

		ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
		defer cancel()
		_, err := client.Cloud.Tasks.Poll(ctx, "task-1")
		if !errors.Is(err, context.DeadlineExceeded) {
			t.Fatalf("Poll error = %v, want context.DeadlineExceeded", err)
		}
	})
}
