// This file is not generated by Stainless and is preserved across codegen runs.
// It holds unit tests for how the hand-written LoadBalancerPoolMember *AndPoll
// helpers interact with a caller-supplied response target (GCLOUD2-27021).
//
// The helpers finish by fetching the member with Get. If the caller's
// WithResponseBodyInto were forwarded to that Get, the request layer would skip
// decoding (requestconfig short-circuits for a **http.Response target, and
// decodes into the caller's value for the others), so the helper would hand back
// a nil member with a nil error. The helpers therefore fetch into their own value
// and write the same body to the caller's target afterwards.
//
// The tests are self-contained: each drives a local httptest.Server emulating the
// Cloud async task flow, so they run under a plain `go test` (or `scripts/test`)
// without needing the Prism/Steady mock server.

package cloud_test

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/G-Core/gcore-go"
	"github.com/G-Core/gcore-go/cloud"
	"github.com/G-Core/gcore-go/option"
	"github.com/G-Core/gcore-go/packages/param"
)

const (
	memberAndPollPoolID   = "00000000-0000-4000-8000-0000000000p0"
	memberAndPollMemberID = "00000000-0000-4000-8000-000000000001"
	memberAndPollAddress  = "192.168.1.10"
)

// memberPayload is the member the fake server returns, both on its own and inside
// the collection response.
func memberPayload() map[string]any {
	return map[string]any{
		"id":                  memberAndPollMemberID,
		"address":             memberAndPollAddress,
		"protocol_port":       80,
		"weight":              2,
		"admin_state_up":      true,
		"backup":              false,
		"operating_status":    "NO_MONITOR",
		"provisioning_status": "ACTIVE",
	}
}

// newMemberFlowServer emulates the Cloud async flow for a pool member:
//   - POST/PATCH .../members returns a TaskIDList with actionTasks (pass an empty
//     slice to emulate a no-op update, where the API creates no task)
//   - GET .../tasks/{id} returns a FINISHED task whose created_resources.members
//     carries the member ID
//   - GET .../pools/{pool_id}/members/{member_id} returns the member itself
//   - GET .../pools/{pool_id}/members returns a one-member collection
func newMemberFlowServer(actionTasks []string) *httptest.Server {
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && strings.Contains(r.URL.Path, "/tasks/"):
			_ = json.NewEncoder(w).Encode(map[string]any{
				"id":                "50e2042d-761b-4f5a-b5bf-e11031c747b0",
				"state":             cloud.TaskStateFinished,
				"task_type":         "create_member",
				"created_resources": map[string]any{"members": []string{memberAndPollMemberID}},
			})
		case r.Method == http.MethodGet && strings.HasSuffix(r.URL.Path, "/members"):
			// The collection GET that ReplaceAndPoll finishes with.
			_ = json.NewEncoder(w).Encode(map[string]any{
				"count":   1,
				"results": []map[string]any{memberPayload()},
			})
		case r.Method == http.MethodGet:
			// The per-member GET the single-resource helpers finish with.
			_ = json.NewEncoder(w).Encode(memberPayload())
		default: // the action: POST or PATCH .../members
			_ = json.NewEncoder(w).Encode(map[string]any{"tasks": actionTasks})
		}
	}))
}

func newMemberFlowClient(server *httptest.Server) gcore.Client {
	return gcore.NewClient(
		option.WithBaseURL(server.URL),
		option.WithAPIKey("test"),
		option.WithCloudProjectID(1),
		option.WithCloudRegionID(1),
	)
}

// assertMember checks the value the helper returned, which must be usable
// regardless of what response target the caller passed.
func assertMember(t *testing.T, member *cloud.Member, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if member == nil {
		t.Fatal("returned member is nil: the caller's response target suppressed decoding")
	}
	if member.ID != memberAndPollMemberID {
		t.Errorf("member.ID = %q, want %q", member.ID, memberAndPollMemberID)
	}
	if member.Weight != 2 {
		t.Errorf("member.Weight = %d, want 2", member.Weight)
	}
}

// memberAndPollCall drives one helper against the fake server.
type memberAndPollCall struct {
	name   string
	invoke func(ctx context.Context, client gcore.Client, opts ...option.RequestOption) (*cloud.Member, error)
	tasks  []string
}

func memberAndPollCalls() []memberAndPollCall {
	return []memberAndPollCall{
		{
			name:  "NewAndPoll",
			tasks: []string{"task-1"},
			invoke: func(ctx context.Context, client gcore.Client, opts ...option.RequestOption) (*cloud.Member, error) {
				return client.Cloud.LoadBalancers.Pools.Members.NewAndPoll(ctx, memberAndPollPoolID,
					cloud.LoadBalancerPoolMemberNewParams{Address: memberAndPollAddress, ProtocolPort: 80}, opts...)
			},
		},
		{
			name:  "UpdateAndPoll",
			tasks: []string{"task-1"},
			invoke: func(ctx context.Context, client gcore.Client, opts ...option.RequestOption) (*cloud.Member, error) {
				return client.Cloud.LoadBalancers.Pools.Members.UpdateAndPoll(ctx, memberAndPollMemberID,
					cloud.LoadBalancerPoolMemberUpdateParams{PoolID: memberAndPollPoolID, Weight: param.NewOpt(int64(2))}, opts...)
			},
		},
		{
			// A PATCH that changes nothing creates no task; the helper skips polling
			// and goes straight to Get, and must still return the member.
			name:  "UpdateAndPoll/no-op",
			tasks: []string{},
			invoke: func(ctx context.Context, client gcore.Client, opts ...option.RequestOption) (*cloud.Member, error) {
				return client.Cloud.LoadBalancers.Pools.Members.UpdateAndPoll(ctx, memberAndPollMemberID,
					cloud.LoadBalancerPoolMemberUpdateParams{PoolID: memberAndPollPoolID}, opts...)
			},
		},
	}
}

// Scenario 1 — no response target (plain SDK use, as in examples/): the helper
// returns the member.
func TestMemberAndPoll_NoResponseTarget(t *testing.T) {
	for _, call := range memberAndPollCalls() {
		t.Run(call.name, func(t *testing.T) {
			server := newMemberFlowServer(call.tasks)
			defer server.Close()

			member, err := call.invoke(context.Background(), newMemberFlowClient(server))
			assertMember(t, member, err)
		})
	}
}

// Scenario 2 — **http.Response target (what the Terraform provider passes):
// the helper returns the member AND fills the caller's response.
func TestMemberAndPoll_HTTPResponseTarget(t *testing.T) {
	for _, call := range memberAndPollCalls() {
		t.Run(call.name, func(t *testing.T) {
			server := newMemberFlowServer(call.tasks)
			defer server.Close()

			res := new(http.Response)
			member, err := call.invoke(context.Background(), newMemberFlowClient(server),
				option.WithResponseBodyInto(&res))
			assertMember(t, member, err)

			if res == nil || res.Body == nil {
				t.Fatal("caller's *http.Response was not populated")
			}
			body, readErr := io.ReadAll(res.Body)
			if readErr != nil {
				t.Fatalf("reading caller's response body: %v", readErr)
			}
			var got cloud.Member
			if err := json.Unmarshal(body, &got); err != nil {
				t.Fatalf("caller's response body is not a member: %v (%s)", err, body)
			}
			if got.ID != memberAndPollMemberID {
				t.Errorf("caller's response body has ID %q, want %q", got.ID, memberAndPollMemberID)
			}
		})
	}
}

// Scenario 3 — *[]byte target (what the CLI passes): the helper returns the
// member AND fills the caller's byte slice.
func TestMemberAndPoll_ByteSliceTarget(t *testing.T) {
	for _, call := range memberAndPollCalls() {
		t.Run(call.name, func(t *testing.T) {
			server := newMemberFlowServer(call.tasks)
			defer server.Close()

			var raw []byte
			member, err := call.invoke(context.Background(), newMemberFlowClient(server),
				option.WithResponseBodyInto(&raw))
			assertMember(t, member, err)

			if len(raw) == 0 {
				t.Fatal("caller's []byte target was not populated")
			}
			var got cloud.Member
			if err := json.Unmarshal(raw, &got); err != nil {
				t.Fatalf("caller's bytes are not a member: %v (%s)", err, raw)
			}
			if got.ID != memberAndPollMemberID {
				t.Errorf("caller's bytes have ID %q, want %q", got.ID, memberAndPollMemberID)
			}
		})
	}
}

// Scenario 4 — typed target: a caller that wants both the return value and its
// own decoded copy gets both.
func TestMemberAndPoll_TypedTarget(t *testing.T) {
	for _, call := range memberAndPollCalls() {
		t.Run(call.name, func(t *testing.T) {
			server := newMemberFlowServer(call.tasks)
			defer server.Close()

			var into cloud.Member
			member, err := call.invoke(context.Background(), newMemberFlowClient(server),
				option.WithResponseBodyInto(&into))
			assertMember(t, member, err)

			if into.ID != memberAndPollMemberID {
				t.Errorf("caller's typed target has ID %q, want %q", into.ID, memberAndPollMemberID)
			}
			if into.Weight != 2 {
				t.Errorf("caller's typed target has Weight %d, want 2", into.Weight)
			}
		})
	}
}

// ReplaceAndPoll returns a collection rather than a single member, so it gets its own
// assertions: the resulting members come back, and the caller's target receives the
// list payload. The no-task case is the API's no-op (the requested set already matches).
func TestMemberReplaceAndPoll(t *testing.T) {
	cases := []struct {
		name  string
		tasks []string
	}{
		{"one task", []string{"task-1"}},
		{"no task (unchanged set)", []string{}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			server := newMemberFlowServer(tc.tasks)
			defer server.Close()
			client := newMemberFlowClient(server)

			// no response target
			members, err := client.Cloud.LoadBalancers.Pools.Members.ReplaceAndPoll(context.Background(),
				memberAndPollPoolID, cloud.LoadBalancerPoolMemberReplaceParams{})
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if len(members) != 1 || members[0].ID != memberAndPollMemberID {
				t.Fatalf("returned members = %+v, want one member with ID %q", members, memberAndPollMemberID)
			}

			// **http.Response target: the return must survive and the caller's body must carry the list
			res := new(http.Response)
			members, err = client.Cloud.LoadBalancers.Pools.Members.ReplaceAndPoll(context.Background(),
				memberAndPollPoolID, cloud.LoadBalancerPoolMemberReplaceParams{},
				option.WithResponseBodyInto(&res))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if len(members) != 1 {
				t.Fatal("returned members is empty: the caller's response target suppressed decoding")
			}
			body, readErr := io.ReadAll(res.Body)
			if readErr != nil {
				t.Fatalf("reading caller's response body: %v", readErr)
			}
			var page struct {
				Count   int64          `json:"count"`
				Results []cloud.Member `json:"results"`
			}
			if err := json.Unmarshal(body, &page); err != nil {
				t.Fatalf("caller's response body is not a member list: %v (%s)", err, body)
			}
			if len(page.Results) != 1 || page.Results[0].ID != memberAndPollMemberID {
				t.Errorf("caller's response body = %s, want one member with ID %q", body, memberAndPollMemberID)
			}
		})
	}
}
