// This file is not generated by Stainless and is preserved across codegen runs.
// It holds unit tests for the no-op handling in the hand-written *UpdateAndPoll
// convenience methods (GCLOUD2-27266).
//
// The Cloud API skips task creation when an update does not change the resource
// (e.g. a tags-only update), returning HTTP 200 with an empty task list. The
// UpdateAndPoll helpers must treat that as a completed no-op — return the
// current resource via Get instead of erroring on the missing task.
//
// The tests are self-contained: each drives a local httptest.Server that
// emulates the Cloud async task flow, so they run under a plain `go test` (or
// `scripts/test`) without needing the Prism/Steady mock server.

package cloud_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/G-Core/gcore-go"
	"github.com/G-Core/gcore-go/cloud"
	"github.com/G-Core/gcore-go/option"
)

const updateAndPollResourceID = "00000000-0000-4000-8000-000000000001"

// newUpdateFlowServer emulates the Cloud async flow for an update:
//   - the PATCH action returns a TaskIDList with the given task IDs (pass an
//     empty slice to emulate a no-op update where the API creates no task)
//   - GET .../tasks/{id} returns a FINISHED task
//   - any other GET (the final resource fetch) returns a permissive object that
//     unmarshals into every resource type
func newUpdateFlowServer(actionTasks []string) *httptest.Server {
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.Method == http.MethodGet && strings.Contains(r.URL.Path, "/tasks/"):
			// Shape captured from a real FINISHED update_router task on the Cloud API.
			_ = json.NewEncoder(w).Encode(map[string]any{
				"id":                  "6465bbb6-6009-4f2c-89e5-4ccffabdf98f",
				"state":               cloud.TaskStateFinished,
				"task_type":           "update_router",
				"client_id":           3621,
				"user_id":             4585,
				"user_client_id":      3621,
				"project_id":          379987,
				"region_id":           76,
				"detailed_state":      nil,
				"request_id":          "a5700e8820e3f8d6e30d8d814472a0ea",
				"error":               nil,
				"created_on":          "2026-07-01T13:33:36",
				"updated_on":          "2026-07-01T13:33:37",
				"finished_on":         "2026-07-01T13:33:37",
				"acknowledged_at":     nil,
				"acknowledged_by":     nil,
				"job_id":              nil,
				"schedule_id":         nil,
				"lifecycle_policy_id": nil,
			})
		case r.Method == http.MethodGet:
			_, _ = w.Write([]byte(`{}`))
		default: // the update action
			_ = json.NewEncoder(w).Encode(map[string]any{"tasks": actionTasks})
		}
	}))
}

func newUpdateFlowClient(server *httptest.Server) gcore.Client {
	return gcore.NewClient(
		option.WithBaseURL(server.URL),
		option.WithAPIKey("test"),
		// Project/region defaults satisfy the required path params that the
		// generated methods validate before issuing a request.
		option.WithCloudProjectID(1),
		option.WithCloudRegionID(1),
	)
}

// updateAndPollMethods enumerates every *UpdateAndPoll method. Each invoke drives
// the method with zero-value params (the fake server ignores request bodies) and
// returns only the error so the tests can assert success uniformly.
var updateAndPollMethods = []struct {
	name   string
	invoke func(ctx context.Context, client gcore.Client) error
}{
	{"DatabasePostgresCluster.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Databases.Postgres.Clusters.UpdateAndPoll(ctx, "id", cloud.DatabasePostgresClusterUpdateParams{})
		return err
	}},
	{"FileShare.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FileShares.UpdateAndPoll(ctx, "id", cloud.FileShareUpdateParams{})
		return err
	}},
	{"FloatingIP.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.FloatingIPs.UpdateAndPoll(ctx, "id", cloud.FloatingIPUpdateParams{})
		return err
	}},
	{"InferenceDeployment.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Inference.Deployments.UpdateAndPoll(ctx, "id", cloud.InferenceDeploymentUpdateParams{})
		return err
	}},
	{"K8SCluster.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.K8S.Clusters.UpdateAndPoll(ctx, "id", cloud.K8SClusterUpdateParams{})
		return err
	}},
	{"LoadBalancerL7Policy.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.L7Policies.UpdateAndPoll(ctx, "id", cloud.LoadBalancerL7PolicyUpdateParams{})
		return err
	}},
	{"LoadBalancerListener.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Listeners.UpdateAndPoll(ctx, "id", cloud.LoadBalancerListenerUpdateParams{})
		return err
	}},
	{"LoadBalancerPool.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.LoadBalancers.Pools.UpdateAndPoll(ctx, "id", cloud.LoadBalancerPoolUpdateParams{})
		return err
	}},
	{"NetworkRouter.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.Networks.Routers.UpdateAndPoll(ctx, "id", cloud.NetworkRouterUpdateParams{})
		return err
	}},
	{"SecurityGroup.UpdateAndPoll", func(ctx context.Context, client gcore.Client) error {
		_, err := client.Cloud.SecurityGroups.UpdateAndPoll(ctx, "id", cloud.SecurityGroupUpdateParams{})
		return err
	}},
}

// TestUpdateAndPollNoOp is the core regression for GCLOUD2-27266: an update that
// creates no task (empty task list) must succeed as a no-op rather than erroring
// with "expected at least one task to be created".
func TestUpdateAndPollNoOp(t *testing.T) {
	server := newUpdateFlowServer([]string{}) // no task created
	defer server.Close()
	client := newUpdateFlowClient(server)

	for _, tc := range updateAndPollMethods {
		t.Run(tc.name, func(t *testing.T) {
			if err := tc.invoke(context.Background(), client); err != nil {
				t.Fatalf("%s should treat an empty task list as a successful no-op, got error: %s", tc.name, err)
			}
		})
	}
}

// TestUpdateAndPollWithTask covers the normal path: the update creates a task,
// which is polled to completion before returning the refreshed resource.
func TestUpdateAndPollWithTask(t *testing.T) {
	server := newUpdateFlowServer([]string{"task-1"})
	defer server.Close()
	client := newUpdateFlowClient(server)

	for _, tc := range updateAndPollMethods {
		t.Run(tc.name, func(t *testing.T) {
			if err := tc.invoke(context.Background(), client); err != nil {
				t.Fatalf("%s returned an unexpected error: %s", tc.name, err)
			}
		})
	}
}

// TestUpdateAndPollMethodsCount is a canary: if codegen or a spec change adds or
// removes an *UpdateAndPoll method, this reminds us to keep the table in sync.
func TestUpdateAndPollMethodsCount(t *testing.T) {
	const want = 10
	if got := len(updateAndPollMethods); got != want {
		t.Fatalf("updateAndPollMethods has %d entries, want %d; update the table in this file", got, want)
	}
}
