// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package gcore

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"reflect"

	"github.com/stainless-sdks/gcore-go/internal/apijson"
	"github.com/stainless-sdks/gcore-go/internal/param"
	"github.com/stainless-sdks/gcore-go/internal/requestconfig"
	"github.com/stainless-sdks/gcore-go/option"
	"github.com/stainless-sdks/gcore-go/shared"
	"github.com/tidwall/gjson"
)

// CloudV2PricingService contains methods and other services that help with
// interacting with the gcore API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewCloudV2PricingService] method instead.
type CloudV2PricingService struct {
	Options   []option.RequestOption
	Inference *CloudV2PricingInferenceService
	K8s       *CloudV2PricingK8Service
}

// NewCloudV2PricingService generates a new service that applies the given options
// to each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewCloudV2PricingService(opts ...option.RequestOption) (r *CloudV2PricingService) {
	r = &CloudV2PricingService{}
	r.Options = opts
	r.Inference = NewCloudV2PricingInferenceService(opts...)
	r.K8s = NewCloudV2PricingK8Service(opts...)
	return
}

// Get billing price of the cluster
func (r *CloudV2PricingService) GetK8sClusterPrice(ctx context.Context, projectID int64, regionID int64, clusterName string, opts ...option.RequestOption) (res *ResourcesPricing, err error) {
	opts = append(r.Options[:], opts...)
	if clusterName == "" {
		err = errors.New("missing required cluster_name parameter")
		return
	}
	path := fmt.Sprintf("cloud/v2/pricing/%v/%v/k8s/clusters/%s", projectID, regionID, clusterName)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

// Preview billing price of the server instance
func (r *CloudV2PricingService) PreviewInstancePrice(ctx context.Context, projectID int64, regionID int64, body CloudV2PricingPreviewInstancePriceParams, opts ...option.RequestOption) (res *InstancePricingPreviewV2, err error) {
	opts = append(r.Options[:], opts...)
	path := fmt.Sprintf("cloud/v2/pricing/%v/%v/instances", projectID, regionID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Preview billing price of the cluster based on the provided configuration.
func (r *CloudV2PricingService) PreviewK8sClusterPrice(ctx context.Context, projectID int64, regionID int64, body CloudV2PricingPreviewK8sClusterPriceParams, opts ...option.RequestOption) (res *ResourcesPricing, err error) {
	opts = append(r.Options[:], opts...)
	path := fmt.Sprintf("cloud/v2/pricing/%v/%v/k8s/clusters", projectID, regionID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Preview billing price of the load balancer.
func (r *CloudV2PricingService) PreviewLoadBalancerPrice(ctx context.Context, projectID int64, regionID int64, body CloudV2PricingPreviewLoadBalancerPriceParams, opts ...option.RequestOption) (res *CloudV2PricingPreviewLoadBalancerPriceResponse, err error) {
	opts = append(r.Options[:], opts...)
	path := fmt.Sprintf("cloud/v2/pricing/%v/%v/loadbalancers", projectID, regionID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Pricing schema with detailed prices per category.
type DetailedLoadBalancerPricing struct {
	// Price of external/public IP over the specified period of time.
	ExternalIP DetailedLoadBalancerPricingExternalIPUnion `json:"external_ip,nullable"`
	// Price of load balancer over the specified period of time.
	Flavor DetailedLoadBalancerPricingFlavorUnion `json:"flavor,nullable"`
	// Price of floating IP over the specified period of time.
	FloatingIP DetailedLoadBalancerPricingFloatingIPUnion `json:"floating_ip,nullable"`
	JSON       detailedLoadBalancerPricingJSON            `json:"-"`
}

// detailedLoadBalancerPricingJSON contains the JSON metadata for the struct
// [DetailedLoadBalancerPricing]
type detailedLoadBalancerPricingJSON struct {
	ExternalIP  apijson.Field
	Flavor      apijson.Field
	FloatingIP  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *DetailedLoadBalancerPricing) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r detailedLoadBalancerPricingJSON) RawJSON() string {
	return r.raw
}

// Price of external/public IP over the specified period of time.
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type DetailedLoadBalancerPricingExternalIPUnion interface {
	ImplementsDetailedLoadBalancerPricingExternalIPUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*DetailedLoadBalancerPricingExternalIPUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

// Price of load balancer over the specified period of time.
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type DetailedLoadBalancerPricingFlavorUnion interface {
	ImplementsDetailedLoadBalancerPricingFlavorUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*DetailedLoadBalancerPricingFlavorUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

// Price of floating IP over the specified period of time.
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type DetailedLoadBalancerPricingFloatingIPUnion interface {
	ImplementsDetailedLoadBalancerPricingFloatingIPUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*DetailedLoadBalancerPricingFloatingIPUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

// Billing response preview schema for loadbalancer
type CloudV2PricingPreviewLoadBalancerPriceResponse struct {
	// Actual discount relative value
	DiscountPercent CloudV2PricingPreviewLoadBalancerPriceResponseDiscountPercentUnion `json:"discount_percent,required,nullable"`
	// Prices per category charged per hour
	PerHour DetailedLoadBalancerPricing `json:"per_hour,required"`
	// Prices per category charged per month
	PerMonth DetailedLoadBalancerPricing `json:"per_month,required"`
	// Price status for the UI
	PriceStatus PriceDisplayStatus `json:"price_status,required"`
	// Currency code (3 letter code per ISO 4217)
	CurrencyCode CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode `json:"currency_code,nullable"`
	// Total price VAT inclusive per month without discount
	PriceWithoutDiscountPerMonth CloudV2PricingPreviewLoadBalancerPriceResponsePriceWithoutDiscountPerMonthUnion `json:"price_without_discount_per_month,nullable"`
	// Total price VAT inclusive per hour
	TotalPricePerHour CloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerHourUnion `json:"total_price_per_hour,nullable"`
	// Total price VAT inclusive per month
	TotalPricePerMonth CloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerMonthUnion `json:"total_price_per_month,nullable"`
	JSON               cloudV2PricingPreviewLoadBalancerPriceResponseJSON                    `json:"-"`
}

// cloudV2PricingPreviewLoadBalancerPriceResponseJSON contains the JSON metadata
// for the struct [CloudV2PricingPreviewLoadBalancerPriceResponse]
type cloudV2PricingPreviewLoadBalancerPriceResponseJSON struct {
	DiscountPercent              apijson.Field
	PerHour                      apijson.Field
	PerMonth                     apijson.Field
	PriceStatus                  apijson.Field
	CurrencyCode                 apijson.Field
	PriceWithoutDiscountPerMonth apijson.Field
	TotalPricePerHour            apijson.Field
	TotalPricePerMonth           apijson.Field
	raw                          string
	ExtraFields                  map[string]apijson.Field
}

func (r *CloudV2PricingPreviewLoadBalancerPriceResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r cloudV2PricingPreviewLoadBalancerPriceResponseJSON) RawJSON() string {
	return r.raw
}

// Actual discount relative value
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type CloudV2PricingPreviewLoadBalancerPriceResponseDiscountPercentUnion interface {
	ImplementsCloudV2PricingPreviewLoadBalancerPriceResponseDiscountPercentUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*CloudV2PricingPreviewLoadBalancerPriceResponseDiscountPercentUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

// Currency code (3 letter code per ISO 4217)
type CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode string

const (
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAed CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AED"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAfn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AFN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAll CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ALL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAmd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AMD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAng CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ANG"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAoa CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AOA"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeArs CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ARS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAud CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AUD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAwg CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AWG"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAzn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "AZN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBam CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BAM"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBbd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BBD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBdt CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BDT"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBgn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BGN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBhd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BHD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBif CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BIF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBmd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BMD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBnd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BND"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBob CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BOB"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBrl CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BRL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBsd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BSD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBtn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BTN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBwp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BWP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeByn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BYN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBzd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "BZD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCad CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CAD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCdf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CDF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeChf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CHF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeClp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CLP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCny CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CNY"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCop CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "COP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCrc CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CRC"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCuc CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CUC"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCup CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CUP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCve CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CVE"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCzk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "CZK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDjf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "DJF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDkk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "DKK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDop CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "DOP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDzd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "DZD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeEgp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "EGP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeErn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ERN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeEtb CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ETB"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeEur CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "EUR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeFjd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "FJD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeFkp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "FKP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGbp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GBP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGel CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GEL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGhs CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GHS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGip CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GIP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGmd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GMD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGnf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GNF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGtq CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GTQ"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGyd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "GYD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHkd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "HKD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHnl CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "HNL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHrk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "HRK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHtg CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "HTG"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHuf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "HUF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIdr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "IDR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIls CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ILS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeInr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "INR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIqd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "IQD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIrr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "IRR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIsk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ISK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeJmd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "JMD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeJod CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "JOD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeJpy CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "JPY"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKes CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KES"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKgs CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KGS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKhr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KHR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKmf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KMF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKpw CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KPW"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKrw CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KRW"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKwd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KWD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKyd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KYD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKzt CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "KZT"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLak CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "LAK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLbp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "LBP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLkr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "LKR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLrd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "LRD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLsl CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "LSL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLyd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "LYD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMad CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MAD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMdl CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MDL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMga CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MGA"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMkd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MKD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMmk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MMK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMnt CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MNT"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMop CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MOP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMro CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MRO"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMur CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MUR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMvr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MVR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMwk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MWK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMxn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MXN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMyr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MYR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMzn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "MZN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNad CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "NAD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNgn CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "NGN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNio CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "NIO"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNok CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "NOK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNpr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "NPR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNzd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "NZD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeOmr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "OMR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePab CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PAB"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePen CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PEN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePgk CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PGK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePhp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PHP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePkr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PKR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePln CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PLN"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePyg CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "PYG"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeQar CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "QAR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRon CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "RON"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRsd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "RSD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRub CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "RUB"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRwf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "RWF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSar CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SAR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSbd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SBD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeScr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SCR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSdg CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SDG"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSek CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SEK"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSgd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SGD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeShp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SHP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSll CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SLL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSos CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SOS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSrd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SRD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSsp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SSP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeStd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "STD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSvc CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SVC"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSyp CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SYP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSzl CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "SZL"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeThb CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "THB"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTjs CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TJS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTmt CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TMT"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTnd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TND"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTop CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TOP"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTry CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TRY"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTtd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TTD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTwd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TWD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTzs CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "TZS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUah CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "UAH"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUgx CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "UGX"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUsd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "USD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUyu CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "UYU"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUzs CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "UZS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeVef CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "VEF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeVnd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "VND"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeVuv CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "VUV"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeWst CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "WST"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXaf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XAF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXag CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XAG"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXau CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XAU"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXba CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XBA"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXbb CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XBB"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXbc CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XBC"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXbd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XBD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXcd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XCD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXdr CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XDR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXof CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XOF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXpd CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XPD"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXpf CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XPF"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXpt CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XPT"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXsu CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XSU"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXts CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XTS"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXua CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XUA"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXxx CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "XXX"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeYer CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "YER"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeZar CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ZAR"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeZmw CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ZMW"
	CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeZwl CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode = "ZWL"
)

func (r CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCode) IsKnown() bool {
	switch r {
	case CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAed, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAfn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAll, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAmd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAng, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAoa, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeArs, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAud, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAwg, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeAzn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBam, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBbd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBdt, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBgn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBhd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBif, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBmd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBnd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBob, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBrl, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBsd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBtn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBwp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeByn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeBzd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCad, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCdf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeChf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeClp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCny, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCop, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCrc, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCuc, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCup, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCve, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeCzk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDjf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDkk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDop, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeDzd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeEgp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeErn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeEtb, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeEur, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeFjd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeFkp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGbp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGel, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGhs, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGip, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGmd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGnf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGtq, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeGyd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHkd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHnl, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHrk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHtg, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeHuf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIdr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIls, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeInr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIqd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIrr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeIsk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeJmd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeJod, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeJpy, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKes, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKgs, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKhr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKmf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKpw, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKrw, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKwd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKyd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeKzt, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLak, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLbp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLkr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLrd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLsl, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeLyd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMad, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMdl, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMga, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMkd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMmk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMnt, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMop, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMro, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMur, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMvr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMwk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMxn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMyr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeMzn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNad, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNgn, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNio, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNok, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNpr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeNzd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeOmr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePab, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePen, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePgk, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePhp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePkr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePln, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodePyg, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeQar, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRon, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRsd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRub, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeRwf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSar, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSbd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeScr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSdg, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSek, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSgd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeShp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSll, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSos, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSrd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSsp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeStd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSvc, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSyp, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeSzl, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeThb, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTjs, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTmt, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTnd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTop, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTry, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTtd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTwd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeTzs, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUah, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUgx, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUsd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUyu, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeUzs, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeVef, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeVnd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeVuv, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeWst, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXaf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXag, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXau, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXba, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXbb, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXbc, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXbd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXcd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXdr, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXof, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXpd, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXpf, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXpt, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXsu, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXts, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXua, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeXxx, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeYer, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeZar, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeZmw, CloudV2PricingPreviewLoadBalancerPriceResponseCurrencyCodeZwl:
		return true
	}
	return false
}

// Total price VAT inclusive per month without discount
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type CloudV2PricingPreviewLoadBalancerPriceResponsePriceWithoutDiscountPerMonthUnion interface {
	ImplementsCloudV2PricingPreviewLoadBalancerPriceResponsePriceWithoutDiscountPerMonthUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*CloudV2PricingPreviewLoadBalancerPriceResponsePriceWithoutDiscountPerMonthUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

// Total price VAT inclusive per hour
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type CloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerHourUnion interface {
	ImplementsCloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerHourUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*CloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerHourUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

// Total price VAT inclusive per month
//
// Union satisfied by [shared.UnionFloat] or [shared.UnionString].
type CloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerMonthUnion interface {
	ImplementsCloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerMonthUnion()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*CloudV2PricingPreviewLoadBalancerPriceResponseTotalPricePerMonthUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.Number,
			Type:       reflect.TypeOf(shared.UnionFloat(0)),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.String,
			Type:       reflect.TypeOf(shared.UnionString("")),
		},
	)
}

type CloudV2PricingPreviewInstancePriceParams struct {
	// The flavor of the instance.
	Flavor param.Field[string] `json:"flavor,required"`
	// Subnet IPs and floating IPs
	Interfaces param.Field[[]NewVmInterfaceSerializersPydanticUnionParam] `json:"interfaces,required"`
	// A list of instance name templates. Either this or 'names' must be specified.
	NameTemplates param.Field[[]string] `json:"name_templates"`
	// A list of instance names. Either this or 'name_templates' must be specified.
	Names param.Field[[]string] `json:"names"`
	// A list of volumes to be created or used.
	Volumes param.Field[[]InstanceVolumePricingRequestParam] `json:"volumes"`
}

func (r CloudV2PricingPreviewInstancePriceParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CloudV2PricingPreviewK8sClusterPriceParams struct {
	// Cluster pools
	Pools param.Field[[]CloudV2PricingPreviewK8sClusterPriceParamsPool] `json:"pools,required"`
}

func (r CloudV2PricingPreviewK8sClusterPriceParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CloudV2PricingPreviewK8sClusterPriceParamsPool struct {
	// Flavor ID
	FlavorID param.Field[string] `json:"flavor_id,required"`
	// Docker volume size
	BootVolumeSize param.Field[int64] `json:"boot_volume_size"`
	// Docker volume type
	BootVolumeType param.Field[CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType] `json:"boot_volume_type"`
	// Enable public v4 address
	IsPublicIpv4 param.Field[bool] `json:"is_public_ipv4"`
	// Minimum node count
	NodeCount param.Field[int64] `json:"node_count"`
}

func (r CloudV2PricingPreviewK8sClusterPriceParamsPool) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

// Docker volume type
type CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType string

const (
	CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeCold          CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType = "cold"
	CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeSsdHiiops     CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType = "ssd_hiiops"
	CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeSsdLocal      CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType = "ssd_local"
	CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeSsdLowlatency CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType = "ssd_lowlatency"
	CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeStandard      CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType = "standard"
	CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeUltra         CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType = "ultra"
)

func (r CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeType) IsKnown() bool {
	switch r {
	case CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeCold, CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeSsdHiiops, CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeSsdLocal, CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeSsdLowlatency, CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeStandard, CloudV2PricingPreviewK8sClusterPriceParamsPoolsBootVolumeTypeUltra:
		return true
	}
	return false
}

type CloudV2PricingPreviewLoadBalancerPriceParams struct {
	// Load balancer flavor name
	Flavor param.Field[string] `json:"flavor,required"`
	// Floating IP configuration for assignment
	FloatingIP param.Field[NewInterfaceFloatingIPPydanticParam] `json:"floating_ip"`
	// Which subnet should be selected if not specified: IPv4, IPv6 or use dual stack.
	VipIPFamily param.Field[InterfaceIPFamily] `json:"vip_ip_family"`
	// Network ID for load balancer. If not specified, default external network will be
	// used. Mutually exclusive with vip_port_id
	VipNetworkID param.Field[string] `json:"vip_network_id"`
	// Existing Reserved Fixed IP port ID for load balancer. Mutually exclusive with
	// vip_network_id
	VipPortID param.Field[string] `json:"vip_port_id"`
	// Subnet ID for load balancer. If not specified, any subnet from vip_network_id
	// will be selected. Ignored when vip_network_id is not specified.
	VipSubnetID param.Field[string] `json:"vip_subnet_id"`
}

func (r CloudV2PricingPreviewLoadBalancerPriceParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
