name: CI
on:
  push:
    branches-ignore:
      - 'generated'
      - 'codegen/**'
      - 'integrated/**'
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    runs-on: ${{ github.repository == 'stainless-sdks/gcore-go' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Run lints
        run: ./scripts/lint
  test:
    timeout-minutes: 10
    name: test
    runs-on: ${{ github.repository == 'stainless-sdks/gcore-go' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: ./scripts/test
  prevent-debug-release:
    name: Prevent Debug SDK Release
    runs-on: ${{ github.repository == 'stainless-sdks/gcore-go' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    steps:
      - name: Debug Mode Failsafe
        run: |
          echo "This SDK was built in debug mode, this job is a failsafe to prevent releasing debug SDKs"
          echo "Remove 'debug: true' from your Stainless config."
          exit 1
